SELECT SUM(ASSIGNMENT_SUBMISSIONS.DURATION) as total_duration
FROM STUDENTS
JOIN COHORTS ON COHORTS.ID = STUDENTS.COHORT_ID
JOIN ASSIGNMENT_SUBMISSIONS ON STUDENTS.ID = ASSIGNMENT_SUBMISSIONS.STUDENT_ID
WHERE COHORTS.NAME = 'FEB12'